export default [
  {
    _id: "123",
    username: "jasminduong09",
    password: "ReciPals",
    name: "Jasmin",
    role: "USER",
    bio: "Cooking with efficiency, exploring with diversity <3",
    tags: ["Student Chef", "Fusion Explorer", "Sustainable"],
    profile: "/images/profile.png",
    posts: ["jd-P1"],
    saved_recipes: [],
    followers: [],
    following: [],
  },
  {
    "_id": "234",
    "username": "danieljacob",
    "password": "ReciPals",
    "name": "Danny",
    "role": "USER",
    "bio": "",
    "tags": [],
    "profile": "/images/profile.png",
    "posts": [],
    "saved_recipes": [],
    "followers": [],
    "following": []
  },
  {
    _id: "recipeBot",
    username: "recipe_bot",
    password: "ReciPals",
    name: "Recipe Bot",
    bio: "Love to cook and bake all things <3",
    tags: ["Baker", "Fusion Explorer", "Sustainable"],
    profile: "/images/recipeBot.png",
    posts: [
      "recipeBot-P1",
      "recipeBot-P2",
      "recipeBot-P3",
      "recipeBot-P4",
      "recipeBot-P5",
      "recipeBot-P6",
      "recipeBot-P7",
      "recipeBot-P8",
      "recipeBot-P9",
      "recipeBot-P10",
      "recipeBot-P11",
      "recipeBot-P12",
      "recipeBot-P13",
      "recipeBot-P14",
      "recipeBot-P15",
      "recipeBot-P16",
      "recipeBot-P17",
      "recipeBot-P18",
      "recipeBot-P19",
      "recipeBot-P20",
      "recipeBot-P21",
      "recipeBot-P22",
      "recipeBot-P23",
      "recipeBot-P24",
      "recipeBot-P25",
      "recipeBot-P26",
      "recipeBot-P27",
      "recipeBot-P28",
      "recipeBot-P29",
      "recipeBot-P30",
      "recipeBot-P31",
      "recipeBot-P32",
      "recipeBot-P33",
      "recipeBot-P34",
      "recipeBot-P35",
      "recipeBot-P36",
      "recipeBot-P37",
      "recipeBot-P38",
      "recipeBot-P39",
      "recipeBot-P40",
      "recipeBot-P41",
      "recipeBot-P42",
      "recipeBot-P43",
      "recipeBot-P44",
      "recipeBot-P45",
      "recipeBot-P46",
      "recipeBot-P47",
      "recipeBot-P48",
      "recipeBot-P49",
      "recipeBot-P50",
      "recipeBot-P51",
      "recipeBot-P52",
      "recipeBot-P53",
      "recipeBot-P54",
      "recipeBot-P55",
      "recipeBot-P56",
      "recipeBot-P57",
      "recipeBot-P58",
      "recipeBot-P59",
      "recipeBot-P60",
      "recipeBot-P61",
      "recipeBot-P62",
      "recipeBot-P63",
      "recipeBot-P64",
      "recipeBot-P65",
      "recipeBot-P66",
      "recipeBot-P67",
      "recipeBot-P68",
      "recipeBot-P69",
      "recipeBot-P70",
      "recipeBot-P71",
      "recipeBot-P72",
      "recipeBot-P73",
      "recipeBot-P74",
      "recipeBot-P75",
      "recipeBot-P76",
      "recipeBot-P77",
      "recipeBot-P78",
      "recipeBot-P79",
      "recipeBot-P80",
      "recipeBot-P81",
      "recipeBot-P82",
      "recipeBot-P83",
      "recipeBot-P84",
      "recipeBot-P85",
      "recipeBot-P86",
      "recipeBot-P87",
      "recipeBot-P88",
      "recipeBot-P89",
      "recipeBot-P90",
      "recipeBot-P91",
      "recipeBot-P92",
      "recipeBot-P93",
      "recipeBot-P94",
      "recipeBot-P95",
      "recipeBot-P96",
      "recipeBot-P97",
      "recipeBot-P98",
      "recipeBot-P99",
      "recipeBot-P100",
      "recipeBot-P101",
      "recipeBot-P102",
      "recipeBot-P103",
      "recipeBot-P104",
      "recipeBot-P105",
      "recipeBot-P106",
      "recipeBot-P107",
      "recipeBot-P108",
      "recipeBot-P109",
      "recipeBot-P110",
      "recipeBot-P111",
      "recipeBot-P112",
      "recipeBot-P113",
      "recipeBot-P114",
      "recipeBot-P115",
      "recipeBot-P116",
      "recipeBot-P117",
      "recipeBot-P118",
      "recipeBot-P119",
      "recipeBot-P120",
      "recipeBot-P121",
      "recipeBot-P122",
      "recipeBot-P123",
      "recipeBot-P124",
      "recipeBot-P125",
      "recipeBot-P126",
      "recipeBot-P127",
      "recipeBot-P128",
      "recipeBot-P129",
      "recipeBot-P130",
      "recipeBot-P131",
      "recipeBot-P132",
      "recipeBot-P133",
      "recipeBot-P134",
      "recipeBot-P135",
      "recipeBot-P136",
      "recipeBot-P137",
      "recipeBot-P138",
      "recipeBot-P139",
      "recipeBot-P140",
      "recipeBot-P141",
      "recipeBot-P142",
      "recipeBot-P143",
      "recipeBot-P144",
      "recipeBot-P145",
      "recipeBot-P146",
      "recipeBot-P147",
      "recipeBot-P148",
      "recipeBot-P149",
      "recipeBot-P150",
      "recipeBot-P151",
      "recipeBot-P152",
      "recipeBot-P153",
      "recipeBot-P154",
      "recipeBot-P155",
      "recipeBot-P156",
      "recipeBot-P157",
      "recipeBot-P158",
      "recipeBot-P159",
      "recipeBot-P160",
      "recipeBot-P161",
      "recipeBot-P162",
      "recipeBot-P163",
      "recipeBot-P164",
      "recipeBot-P165",
      "recipeBot-P166",
      "recipeBot-P167",
      "recipeBot-P168",
      "recipeBot-P169",
      "recipeBot-P170",
      "recipeBot-P171",
      "recipeBot-P172",
      "recipeBot-P173",
      "recipeBot-P174",
      "recipeBot-P175",
      "recipeBot-P176",
      "recipeBot-P177",
      "recipeBot-P178",
      "recipeBot-P179",
      "recipeBot-P180",
      "recipeBot-P181",
      "recipeBot-P182",
      "recipeBot-P183",
      "recipeBot-P184",
      "recipeBot-P185",
      "recipeBot-P186",
      "recipeBot-P187",
      "recipeBot-P188",
      "recipeBot-P189",
      "recipeBot-P190",
      "recipeBot-P191",
      "recipeBot-P192",
      "recipeBot-P193",
      "recipeBot-P194",
      "recipeBot-P195",
      "recipeBot-P196",
      "recipeBot-P197",
      "recipeBot-P198",
      "recipeBot-P199",
      "recipeBot-P200",
      "recipeBot-P201",
      "recipeBot-P202",
      "recipeBot-P203",
      "recipeBot-P204",
      "recipeBot-P205",
      "recipeBot-P206",
      "recipeBot-P207",
      "recipeBot-P208",
      "recipeBot-P209",
      "recipeBot-P210",
      "recipeBot-P211",
      "recipeBot-P212",
      "recipeBot-P213",
      "recipeBot-P214",
      "recipeBot-P215",
      "recipeBot-P216",
      "recipeBot-P217",
      "recipeBot-P218",
      "recipeBot-P219",
      "recipeBot-P220",
      "recipeBot-P221",
      "recipeBot-P222",
      "recipeBot-P223",
      "recipeBot-P224",
      "recipeBot-P225",
      "recipeBot-P226",
      "recipeBot-P227",
      "recipeBot-P228",
      "recipeBot-P229",
      "recipeBot-P230",
      "recipeBot-P231",
      "recipeBot-P232",
      "recipeBot-P233",
      "recipeBot-P234",
      "recipeBot-P235",
      "recipeBot-P236",
      "recipeBot-P237",
      "recipeBot-P238",
      "recipeBot-P239",
      "recipeBot-P240",
      "recipeBot-P241",
      "recipeBot-P242",
      "recipeBot-P243",
      "recipeBot-P244",
      "recipeBot-P245",
      "recipeBot-P246",
      "recipeBot-P247",
      "recipeBot-P248",
      "recipeBot-P249",
      "recipeBot-P250",
      "recipeBot-P251",
      "recipeBot-P252",
      "recipeBot-P253",
      "recipeBot-P254",
      "recipeBot-P255",
      "recipeBot-P256",
      "recipeBot-P257",
      "recipeBot-P258",
      "recipeBot-P259",
      "recipeBot-P260",
      "recipeBot-P261",
      "recipeBot-P262",
      "recipeBot-P263",
      "recipeBot-P264",
      "recipeBot-P265",
      "recipeBot-P266",
      "recipeBot-P267",
      "recipeBot-P268",
      "recipeBot-P269",
      "recipeBot-P270",
      "recipeBot-P271",
      "recipeBot-P272",
      "recipeBot-P273",
      "recipeBot-P274",
      "recipeBot-P275",
      "recipeBot-P276",
      "recipeBot-P277",
      "recipeBot-P278",
      "recipeBot-P279",
      "recipeBot-P280",
      "recipeBot-P281",
      "recipeBot-P282",
      "recipeBot-P283",
      "recipeBot-P284",
      "recipeBot-P285",
      "recipeBot-P286",
      "recipeBot-P287",
      "recipeBot-P288",
      "recipeBot-P289",
      "recipeBot-P290",
      "recipeBot-P291",
      "recipeBot-P292",
      "recipeBot-P293",
      "recipeBot-P294",
      "recipeBot-P295",
      "recipeBot-P296",
      "recipeBot-P297",
      "recipeBot-P298",
      "recipeBot-P299",
      "recipeBot-P300",
      "recipeBot-P301",
      "recipeBot-P302",
    ],
    saved_recipes: [],
    followers: [],
    following: [],
  },
];
